apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE DATABASE db_auth;
    CREATE DATABASE db_devices;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "1234"
        # On ne définit plus POSTGRES_DB ici pour laisser le script gérer
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: init-script
        configMap:
          name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
spec:
  selector:
    app: postgres-auth
  ports:
  - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-devices
spec:
  selector:
    app: postgres-auth
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-auth
  template:
    metadata:
      labels:
        app: redis-auth
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-auth
spec:
  selector:
    app: redis-auth
  ports:
  - port: 6379
---
# MongoDB & RabbitMQ (inchangés)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-monitoring
  template:
    metadata:
      labels:
        app: mongo-monitoring
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-monitoring
spec:
  selector:
    app: mongo-monitoring
  ports:
  - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        command: ["/bin/sh", "-c"]
        args:
          - |
            rabbitmq-plugins enable --offline rabbitmq_mqtt rabbitmq_web_mqtt
            exec docker-entrypoint.sh rabbitmq-server
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 1883
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
  - name: management
    port: 15672
  - name: mqtt
    port: 1883
