apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: device-service
  template:
    metadata:
      labels:
        app: device-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: device-service
        image: device-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        env:
        - name: SERVER_DB
          value: "postgres-devices"
        - name: NAME_DB
          value: "db_devices"
---
apiVersion: v1
kind: Service
metadata:
  name: device-service
spec:
  selector:
    app: device-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
    nodePort: 30081
  type: NodePort
